# config.py

VIDEO_PATH = "traffic.mp4"
MODEL_PATH = "yolov8n.pt"

ALLOWED_CLASSES = [0, 2, 3, 5, 7]

LINE_Y = 300
STOP_LINE_Y = 250

FRAME_WIDTH = 640

LOW_DENSITY = 5
MEDIUM_DENSITY = 10

ZONES = {
    "left": (0, FRAME_WIDTH // 2),
    "right": (FRAME_WIDTH // 2, FRAME_WIDTH)
}

SIGNAL = "RED"
DIRECTION_THRESHOLD = 5

# Speed
FPS = 30
PIXEL_TO_METER = 0.05
SPEED_SMOOTHING = 0.8